%% Structs
VEH_STATUS.IDLE=1;
VEH_STATUS.PAUSED=2;
VEH_STATUS.FINISH=3;
VEH_STATUS.IN_ROW=4;
VEH_STATUS.OUT_ROW=5;
VEH_STATUS.EXITING=6;
VEH_STATUS.ENTERING=7;
VEH_STATUS.OBSTACLE_INSIDE =8;
VEH_STATUS.ERROR=9;
VEH_STATUS.MANUAL=255;

INROWDETSTR.TRAJECTORY = 0;
INROWDETSTR.AUTOMATIC = 1;
INROWDETSTR.MANUAL = 2;

LINEFORM.EXPLICIT = 0;
LINEFORM.NORMAL = 1;

FOOTPRINT.length = 2.4;
FOOTPRINT.width = 1.3;

CHUNKSTATE.NO_CHUNK = -1;
CHUNKSTATE.NOT_FITTED = 0;
CHUNKSTATE.FITTED = 1;
CHUNKSTATE.DISCARDED = 2;