figure('Name','Row State', 'NumberTitle','off');
tiledlayout(2,1);

%% VEHICLE STATUS
if isfield(bag1, 'supervisor')
    tiledlayout(3,1);
    ax(f) = nexttile; f = f+1; hold on;
    plot(bag1.supervisor.stamp, double(bag1.supervisor.state),'DisplayName','Trajectory');
    yticks(double([VEH_STATUS.IDLE, ...
                   VEH_STATUS.PAUSED, ...
                   VEH_STATUS.FINISH, ...
                   VEH_STATUS.IN_ROW, ...
                   VEH_STATUS.OUT_ROW, ...
                   VEH_STATUS.EXITING, ...
                   VEH_STATUS.ENTERING, ...
                   VEH_STATUS.OBSTACLE_INSIDE, ...
                   VEH_STATUS.ERROR, ...
                   VEH_STATUS.MANUAL]));
    
    yticklabels({'IDLE', ...
                 'PAUSED', ...
                 'FINISH', ...
                 'IN\_ROW', ...
                 'OUT\_ROW', ...
                 'EXITING', ...
                 'ENTERING', ...
                 'OBSTACLE', ...
                 'ERROR', ...
                 'MANUAL'});
    legend('Location','northwest')
end
%% In row detection strategy

ax(f) = nexttile; f=f+1; hold on; grid on;
plot(bag1.debug.stamp, double(bag1.debug.in_row_det.in_row_det_strategy), 'LineWidth', 1.5, 'DisplayName', 'Bag 1');
if compare
    plot(bag2.debug.stamp, double(bag2.debug.in_row_det.in_row_det_strategy), 'LineWidth', 1.5, 'DisplayName', 'Bag 2');
    legend('Location','northwest');
end
yticks(double([ INROWDETSTR.TRAJECTORY, ...
                INROWDETSTR.AUTOMATIC, ...
                INROWDETSTR.MANUAL]));
yticklabels({'TRAJECTORY', 'AUTOMATIC', 'MANUAL'});


%% In Row State
ax(f) = nexttile; f=f+1; hold on; grid on;

plot(ax(f-1), bag1.debug.stamp, bag1.debug.in_row_det.automatic_in_row, 'LineWidth', 1.5, 'DisplayName', 'Automatic');
plot(ax(f-1), bag1.debug.stamp, bag1.debug.in_row_det.joy_in_row, "LineWidth", 1.5, 'DisplayName', 'Joypad');
plot(ax(f-1), bag1.debug.stamp, bag1.debug.in_row_det.trajectory_in_row, "LineWidth", 1.5, 'DisplayName', 'Trajectory');
if compare
    plot(ax(f-1), bag2.state.stamp, bag2.state.in_row, 'LineWidth', 1.5, 'DisplayName', 'Bag 2');
end
legend('Location','northwest')
ylim([-0.5 1.5]);
ylabel('In-Row State');
xlabel('timestamp [s]');

